### ISSUE TITLE
As a CAS data user, I want to have access to the latest version of Metabase (0.46), so that I can use the latest visualisation features

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-metabase#103]
Acceptance Criteria:

Given I am a CAS member,
When I access the metabase URL
Then I am using the 0.46.6.1 version

We are currently on Metabase v44.2
The latest release of Metabase is v46.6.61

Release: https://github.com/metabase/metabase/releases/tag/v0.46.6.1

Steps:
- [x] run the prod-test restore on metabase test
- [x] run the broken questions script on metabase test to get an error baseline
- [ ] update metabase to the latest version & release to test
- [ ] re-run the broken questions script to see if the upgrade caused issues
- [ ] do a quick manual walkthrough of metabase test
- [ ] verify what new features the UI presents, and advise/train the team if needed (or schedule an information session)
- [ ] release to prod

**Comment by dleard** [comment]
potentially relates to #108
