### ISSUE TITLE
Tech Debt: Update Metabase to the latest version (v48.6)

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-metabase#114]
Metabase is a couple of versions behind.
We don't want to leave this for too long, the upgrade path gets exponentially more difficult as time passes, without risking to lose any data.

Todo:
- [x] review the upgrading instructions: https://www.metabase.com/docs/latest/installation-and-operation/upgrading-metabase
- [x] update Metabase image to the latest release as of today (https://github.com/metabase/metabase/releases/)
- [x] test with a manual deployment in -dev (making sure that the database migrations run smoothly)

**Comment by pbastia** [comment]
@BallardRobinett we can probably split the terraform stuff into another card here

**Comment by pbastia** [comment]
#113  can be tacked after this one

**Comment by patriciarussellCAS** [comment]
Hey @pbastia - Can you confirm that the items listed above in "To do" have been completed? I assume yes but wanted to double check as they aren't checked off.

**Comment by pbastia** [comment]
I confirm!
