### ISSUE TITLE
Task: Renew certificate before March 9th

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-metabase#120]
Metabase cert expires by March 9th and needs to be renewed.
Certbot is no longer an option, so the process is now manual.

Resources:
NRIDS SSL Cert: https://apps.nrs.gov.bc.ca/int/confluence/display/DEVGUILD/SSL+Certificates
NRIDS Generating a CSR: https://apps.nrs.gov.bc.ca/int/confluence/display/DEVGUILD/Generating+a+CSR
@dleard's writeup on getting a brand new certificate: https://bcgov.sharepoint.com/:w:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/OBPS/Domain%20Setup/Domain_Request_and_SSL_Certificate_Documentation.docx?d=w3140fee140ef4eb2abf7615a53fb391e&csf=1&web=1&e=vxstGj

Acceptance criteria:
- [x] New certificate provisioned by middle tier
- [x] OpenShift route updated with certificate information
- [x] Certificate information backed up in the team's 1password (note named 'cas-metabase.nrs.gov.bc.ca 2024 Entrust Certificate')

**Comment by patriciarussellCAS** [comment]
Renewal request submitted to NRIDS on Feb 28 2024. Waiting for confirmation.

**Comment by pbastia** [comment]
@patriciarussellCAS to verify this, visit https://cas-metabase.nrs.gov.bc.ca/ , click the little padlock in the URL bar of your browser and view the certificate information. The validity should be March 4, 2025
