### ISSUE TITLE
Metabase - Database and business intelligence enhancements 

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-metabase#28]
From: https://youtrack.button.is/issue/GGIRCS-1716 
Views and/or dashboards for:
            o    CIIP
            o  Reporting program (SWRS)
            o    Executives
                   -   CIIP program analytics
                   -   CIIP program administration analytics
            o    Public report
                   -   Visualizations
                   -   Maps
                   -   Downloadability/exports/data sharing (where appropriate)?
            o    Data modelling
            o    Others?
   Training
   Data science (e.g., pre 2013 data) – this is complicated.

**Comment by rdromey** [comment]
Talked to Pierre and last two tickets moved to the icebox. Good to close.
