### ISSUE TITLE
Context-specific Metabase Lab Training

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-metabase#30]
To avoid downloading Metabase data in spreadsheets, training needs to be provided to show users how to create dashboards and use Metabase according to their specific use cases/needs.
First we will need to find out what they are downloading and what they are using it for. Then we can tailor training to show them how to do those tasks within Metabase.
There needs to be emphases on data security from an authority. Since permissions are setup in Metabase, those go out the window when tables are downloaded and saved on a LAN for example (anyone with that access can then see the data). We need a data custodian to be present to share the need to put data privacy FIRST and use Metabase as it was intended.

AC Related to setting up Metabase for training:
- [x] Set up team meeting to discuss approach
- [x] Reach out to Hanna and John and Matt in discussion to determine what is of most value to their teams in terms of training
- [x] Create training objectives on Miro board
- [x] Setup metabase data.... 
- [x] Start new Miro board for the lab

Notes:
- UX/Service Design support on creative miro board design
- Additional tickets may stem from this one

**Comment by pbastia** [comment]
Last item to do: take in account the feedback from the trial run with the team and update the miro board with that information

**Comment by LindsayMacfarlane** [comment]
Great work to everyone who designed the training! I'm looking forward to when we can deliver the training to staff :)
