### ISSUE TITLE
Automate metabase prod-test restore

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-metabase#45]
The prod-test restore work is missing a component that makes it work on deploy.
2 cronjobs were created (prod-test-restore & db-pass), but no corresponding dag to run them.
Solution:
Either add a dag to run these cronjobs or refactor the cronjobs into jobs and add a `post-install` hook + hook weights.
If we want to add a dag, then it's related to the work being done in https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/1887

**Comment by LindsayMacfarlane** [comment]
Thanks @dleard for the explanation - no testing required on my end :)
