### ISSUE TITLE
Metabase Training - Scheduling Prep

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-metabase#59]
Acceptance Criteria:
- [x] Reach out to attendees to give them a heads-up and check on availability. Aim = October/November
- [x] schedule training dates: 2x 2 hour sessions (part 1 and part 2 to build off what they learned in 1)
eg: 30 mins of overview + 90 mins ish hands-on
- [x] Send out invites to attendees: RA, ICU, CE

**Comment by pbastia** [comment]
The training as it was planned was mostly CIIP-SWRS centered, it might be good to develop a small CIF example

**Comment by pbastia** [comment]
@LindsayMacfarlane were invites sent out for this?

**Comment by Dianadec** [comment]
@pbastia I don't believe they were.

**Comment by LindsayMacfarlane** [comment]
No, not yet. @Dianadec - is this something you can help me set up and get out before end of sprint?

**Comment by Dianadec** [comment]
@LindsayMacfarlane yes - do we have an updates list of who needs to participate? The AC previously said the branches RA, ICU, CE but that's probably outdated by now. What is the ask for the training? I.e. what are the learning objectives?

**Comment by Dianadec** [comment]
@LindsayMacfarlane yes - do we have an updates list of who needs to participate? The AC previously said the branches RA, ICU, CE but that's probably outdated by now. What is the ask for the training? I.e. what are the learning objectives?

**Comment by Dianadec** [comment]
Attendee tracking list can be found in Scrum team > Files > Training - Metabase

**Comment by Dianadec** [comment]
@pbastia @LindsayMacfarlane  Is this bullet in the AC still accurate for the length of the sessions? Or am I just scheduling one session that is 2 hours in length (= 30 min overview + 90 min hands-on lab). Could also offer two different dates of the same content to be more open for people's scheduling availability.

> schedule training dates: 2x 2 hour sessions (part 1 and part 2 to build off what they learned in 1)
> eg: 30 mins of overview + 90 mins ish hands-on

**Comment by LindsayMacfarlane** [comment]
Thank you so much @Dianadec for getting this all organized! This was so very much appreciated :)
