### ISSUE TITLE
Tech Debt: Test helm yaml for nginx sidecar deployment 

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-metabase#60]
As suggested in #52 by @wenzowski ,
We can add a test that `helm template` runs properly and contains - or not - valid yaml for the nginx sidecar

**Comment by wenzowski** [comment]
Perhaps pulling in [kube-bench](https://github.com/aquasecurity/kube-bench) would provide a [static analysis best practice](https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-9-use-static-analysis-tools) here?

**Comment by dleard** [comment]
closing. nginx sidecar was removed in #84
