### ISSUE TITLE
iStore request for metabase prod cert renewal

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-metabase#70]
Not extremely urgent, the current certificate expires on Jan 29th

**Comment by LindsayMacfarlane** [comment]
Submitted request to NRM Business Service Desk on January 4, 2022.

**Comment by LindsayMacfarlane** [comment]
iStore request has now been submitted by NRM Business Service Desk.

**Comment by matthieu-foucault** [comment]
- [ ] Airflow DAG was re-enabled and the new certificate was issued
- [ ] Metabase pods cycled as the DAG for metabase was not set to reload nginx after a cert issue

**Comment by matthieu-foucault** [comment]
@LindsayMacfarlane this is done, metabase certificate shows:

```
Issued On	Wednesday, January 12, 2022 at 11:58:04 AM
Expires On	Sunday, January 29, 2023 at 11:58:04 AM
```

**Comment by LindsayMacfarlane** [comment]
Awesome! Thank you @matthieu-foucault !
