### ISSUE TITLE
Helm chart linting

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-metabase#85]
The metabase chart is not being linted, which can cause us to accidentally release a broken chart. 

To avoid this:
- [ ] create a `make lint_chart` target that calls `helm template ... --validate`, similarly to the cif one
- [ ] call that target in a GH action
- [ ] make this action a required check when merging PRs

**Comment by LindsayMacfarlane** [comment]
@pbastia @dleard is there any additional details that can be added to this ticket?

**Comment by pbastia** [comment]
@LindsayMacfarlane done! Marked as tech debt and removed the backlog refinement tag

**Comment by mikevespi** [comment]
This has been taken care of at some point. Closing the issue.
