### ISSUE TITLE
As a metabase user, I want to access the prod version through a shorter URL

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-metabase#94]
After an update to production, the nginx container including its associated PVCs were dropped, which means the certificates are gone.

2 options moving forward:
- ~An organizational wildcard certificate will be made available~ not happening any time soon
- The team will need to retrieve the existing certificate that was lost from entrust / re-procure one (the existing one expired in Feb or March)

**Comment by pbastia** [comment]
@LindsayMacfarlane once we have confirmation on whether or not we'll be able to use an organisation-wide wildcard certificate, we'll update this card with details of the work

**Comment by LindsayMacfarlane** [comment]
Hi @pbastia - I feel I was supposed to update this ticket a while back, with an update on the organizational wildcard approach...can you remind me - this route was not possible, correct?

**Comment by pbastia** [comment]
This route was not possible, so the second option is the route we need to go

**Comment by pbastia** [comment]
Done!
