### ISSUE TITLE
As a Metabase maintainer, I want to use certbot to retrieve the certificates, so that I can cut down on the amount of maintenance

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-metabase#97]
## Issue:
Nginx containers and automatic certificate retrieval was removed when the team understood a wildcard certificate was available.
Now that this is not the case, we need to use certbot to retrieve that certificate.
There will be just a little bit of investigation to see if we can use the regular certbot chart, or if a small fork is necessary like we had for ciip.

Certbot repo: https://github.com/BCDevOps/certbot
Example of certbot usage in CIF: https://github.com/bcgov/cas-cif/blob/develop/chart/cas-cif/Chart.yaml

For reference, this is the certbot fork that the team was using: https://github.com/BCDevOps/certbot/commit/6836588e58ccaa1e691de610716bbb8b11c7246d
It just adds a missing role and rolebinding if we need a different user. 

### Acceptance Criteria

As a metabase maintainer
When I setup certificate automation
I want to use certbot

As a Metabase maintainer
When use certbot in my application
I want to make sure it works with the proper roles and rolebindings

### Dev Checklist
- [x] PO to secure funding for certificate
- [ ] Put in iStore request for SSL certificate
- [ ] verify that the official certbot release now implements what the fork was intending on doing
- [ ] if necessary: fork the official repository again with the `bc-cas` user and apply the changes, and contact certbot maintainers to have it merged
- [ ] integrate the official or forked certbot helm chart in metabase (similar to CIF)

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-metabase/97?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @mikevespi @Sepehr-Sobhani @sam-warren

**Comment by LindsayMacfarlane** [comment]
Hi @BCerki @gurjmatharu @mikevespi @Sepehr-Sobhani @sam-warren - flagging this for your estimation.

**Comment by pbastia** [comment]
The first step will be to make it work with let's encrypt for -dev and -test, while a -prod certificate is being procured

**Comment by LindsayMacfarlane** [comment]
@pbastia - Funding approved for our Entrust certificate. Next step will be to put in the istore request (I believe), which I can start.

**Comment by pbastia** [comment]
Do we know how long it takes an iStore request to be approved? We need to make sure we're in a position of retrieving the certificate first (I believe once it's approved we have 2 weeks)

**Comment by LindsayMacfarlane** [comment]
Will depend on our NRIDS capacity. My estimate would be it will take 1-2 weeks...if not a bit longer.

**Comment by dleard** [comment]
@pbastia I have a PR up for this. I think we will need to deploy this normally for dev/test & then for prod, deploy manually with --set certbot.manualRun=true to fire the manual job get us a tracking ID. Also, we will need to update and run cas-provision to add the cas-acme-url secret to the metabase-prod namespace
